version: '3.8'

services:
  # PDF Dify 应用
  pdf-dify-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: pdf-dify-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - opensearch
    networks:
      - pdf-dify-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # OpenSearch 服务
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch-node
    restart: unless-stopped
    environment:
      - cluster.name=pdf-dify-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - pdf-dify-network

  # OpenSearch Dashboards (可选，用于管理和可视化)
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    depends_on:
      - opensearch
    networks:
      - pdf-dify-network

  # Nginx 反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: pdf-dify-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - pdf-dify-app
    networks:
      - pdf-dify-network

volumes:
  opensearch-data:
    driver: local

networks:
  pdf-dify-network:
    driver: bridge
